from app.models.student_status import StudentStatus
from app.models.student import Student
from app.models.career import Career
from app.models.grade import Grade
from app.models.career_grade import CareerGrade
from app.models.study_plan import StudyPlan
from app.models.subject import Subject
from app.models.subject_study_plan import SubjectStudyPlan
from app.models.professor import Professor
from app.models.professor_subject import ProfessorSubject
from app.models.classroom import Classroom
from app.models.enrollment import Enrollment
from app.models.enrollment_subject_classroom import EnrollmentSubjectClassroom